/*
 *  Copyright (c) 2026 Conclusive Engineering Sp. z o.o.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_I2S_TI_CC35XX_I2S_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_I2S_TI_CC35XX_I2S_H_

#define TI_CC35XX_I2S_CLK_SRC_SOC_CLK		0x10
#define TI_CC35XX_I2S_CLK_SRC_SOC_PLL_CLK	0x20
#define TI_CC35XX_I2S_CLK_SRC_HFXT_CLK		0x30

#define TI_CC35XX_I2S_PIN_DIR_DISABLED		0x00
#define TI_CC35XX_I2S_PIN_DIR_INPUT		0x01
#define TI_CC35XX_I2S_PIN_DIR_OUTPUT		0x02

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_I2S_TI_CC35XX_I2S_H_ */
