/*
 * Copyright (c) 2026 Conclusive Engineering Sp. z o.o.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef _TI_CC35XX_SDHC_
#define _TI_CC35XX_SDHC_

enum ti_cc35xx_sdhc_response_type {
	TI_CC35XX_SDHC_RESP_NONE = 0,
	TI_CC35XX_SDHC_RESP_LEN_136,
	TI_CC35XX_SDHC_RESP_LEN_48,
	TI_CC35XX_SDHC_RESP_LEN_48B,
	TI_CC35XX_SDHC_INVAL_HOST_RESP_LEN,
};

#define TI_CC35XX_SD_RSP_TYPE_MASK_SD 0x0f
#define TI_CC35XX_SD_RSP_TYPE_MASK_SPI 0xf0

/*********************/
/* IP SDHC Registers */
/*********************/
/* DMAADDR */
#define TI_CC35XX_SDHC_REG_DMAADDR_ADDR 0x200
/* BLKCFG */
#define TI_CC35XX_SDHC_REG_BLKCFG_ADDR 0x204
#define TI_CC35XX_SDHC_REG_BLKCFG_BLKCNT_L 16
#define TI_CC35XX_SDHC_REG_BLKCFG_BLKCNT_M 0xffff
#define TI_CC35XX_SDHC_REG_BLKCFG_BLKLEN_L 0
#define TI_CC35XX_SDHC_REG_BLKCFG_BLKLEN_M 0x7ff
/* CMDARG */
#define TI_CC35XX_SDHC_REG_CMDARG_ADDR 0x208
/* SDCMD */
#define TI_CC35XX_SDHC_REG_SDCMD_ADDR 0x20c
#define TI_CC35XX_SDHC_REG_SDCMD_CMD_M 0xffff0000
#define TI_CC35XX_SDHC_REG_SDCMD_TRMODE_M 0x0000ffff
#define TI_CC35XX_SDHC_REG_SDCMD_RSPTYPE_L 16
#define TI_CC35XX_SDHC_REG_SDCMD_CMDCRCE_L 19
#define TI_CC35XX_SDHC_REG_SDCMD_IDXCHK_L 20
#define TI_CC35XX_SDHC_REG_SDCMD_DATPRES_L 21
#define TI_CC35XX_SDHC_REG_SDCMD_CMDTYPE_L 22
#define TI_CC35XX_SDHC_REG_SDCMD_CMDIDX_L 24
#define TI_CC35XX_SDHC_REG_SDCMD_BLKSEL BIT(5)
#define TI_CC35XX_SDHC_REG_SDCMD_XFRDIR BIT(4)
#define TI_CC35XX_SDHC_REG_SDCMD_AUTOCMD_L 2
#define TI_CC35XX_SDHC_REG_SDCMD_AUTOCMD_M 0x03
#define TI_CC35XX_SDHC_REG_SDCMD_AUTOCMD_CMD12EN 1
#define TI_CC35XX_SDHC_REG_SDCMD_AUTOCMD_CMD23EN 2
#define TI_CC35XX_SDHC_REG_SDCMD_BLKCNT BIT(1)
/* RSP10 */
#define TI_CC35XX_SDHC_REG_RSP10_ADDR 0x210
/* RSP32 */
#define TI_CC35XX_SDHC_REG_RSP32_ADDR 0x214
/* RSP54 */
#define TI_CC35XX_SDHC_REG_RSP54_ADDR 0x218
/* RSP76 */
#define TI_CC35XX_SDHC_REG_RSP76_ADDR 0x21c
/* DATABUF */
#define TI_CC35XX_SDHC_REG_DATABUF_ADDR 0x220
/* PSTAT */
#define TI_CC35XX_SDHC_REG_PSTAT_ADDR 0x224
#define TI_CC35XX_SDHC_REG_PSTAT_CDINS BIT(16)
#define TI_CC35XX_SDHC_REG_PSTAT_BUFRD BIT(11)
#define TI_CC35XX_SDHC_REG_PSTAT_BUFWREN BIT(10)
#define TI_CC35XX_SDHC_REG_PSTAT_DATALN BIT(2)
#define TI_CC35XX_SDHC_REG_PSTAT_DATCMDINH BIT(1)
#define TI_CC35XX_SDHC_REG_PSTAT_CMDINH BIT(0)
/* HOSTCTL */
#define TI_CC35XX_SDHC_REG_HOSTCTL_ADDR 0x228
#define TI_CC35XX_SDHC_REG_HOSTCTL_BUSVSEL_L 9
#define TI_CC35XX_SDHC_REG_HOSTCTL_BUSVSEL_M 0x7
#define TI_CC35XX_SDHC_REG_HOSTCTL_BUSVSEL_V33 7
#define TI_CC35XX_SDHC_REG_HOSTCTL_BUSVSEL_V30 6
#define TI_CC35XX_SDHC_REG_HOSTCTL_BUSVSEL_V18 5
#define TI_CC35XX_SDHC_REG_HOSTCTL_BUSPOWR BIT(8)
#define TI_CC35XX_SDHC_REG_HOSTCTL_BUSWIDTH BIT(1)
/* SYSCTRL */
#define TI_CC35XX_SDHC_REG_SYSCTRL_ADDR 0x22c
#define TI_CC35XX_SDHC_REG_SYSCTRL_DATATIME_L 16
#define TI_CC35XX_SDHC_REG_SYSCTRL_DATATIME_M 0x0f
#define TI_CC35XX_SDHC_REG_SYSCTRL_DATATIME_MAX 0x0e
#define TI_CC35XX_SDHC_REG_SYSCTRL_CLKDIV_L 6
#define TI_CC35XX_SDHC_REG_SYSCTRL_CLKDIV_M 0x3ff
#define TI_CC35XX_SDHC_REG_SYSCTRL_CLKDIV_MAX 0x3ff
#define TI_CC35XX_SDHC_REG_SYSCTRL_CLKEN BIT(2)
#define TI_CC35XX_SDHC_REG_SYSCTRL_CLKSTAB BIT(1)
#define TI_CC35XX_SDHC_REG_SYSCTRL_INTCLKEN BIT(0)
/* INTSTAT */
#define TI_CC35XX_SDHC_REG_INTSTAT_ADDR 0x230
#define TI_CC35XX_SDHC_REG_INTSTAT_ERR_INT BIT(15)
#define TI_CC35XX_SDHC_REG_INTSTAT_CARD_IRQ BIT(8)
#define TI_CC35XX_SDHC_REG_INTSTAT_CARDREM BIT(7)
#define TI_CC35XX_SDHC_REG_INTSTAT_CARDINS BIT(6)
#define TI_CC35XX_SDHC_REG_INTSTAT_BUFRDY BIT(5)
#define TI_CC35XX_SDHC_REG_INTSTAT_BUFWR BIT(4)
#define TI_CC35XX_SDHC_REG_INTSTAT_DMAINT BIT(3)
#define TI_CC35XX_SDHC_REG_INTSTAT_BLKGAP BIT(2)
#define TI_CC35XX_SDHC_REG_INTSTAT_TRCMP BIT(1)
#define TI_CC35XX_SDHC_REG_INTSTAT_CMDCMPL BIT(0)
#define TI_CC35XX_SDHC_REG_INTSTAT_ALL 0xffffffff
/* INTENAB */
#define TI_CC35XX_SDHC_REG_INTENAB_ADDR 0x234
#define TI_CC35XX_SDHC_REG_INTENAB_ALL 0xffffffff
/* INTSIGEN */
#define TI_CC35XX_SDHC_REG_INTSIGEN_ADDR 0x238
#define TI_CC35XX_SDHC_REG_INTSIGEN_ALL 0xffffffff
/* CAPA */
#define TI_CC35XX_SDHC_REG_CAPA_ADDR 0x240
#define TI_CC35XX_SDHC_REG_CAPA_V18SUPP BIT(26)
#define TI_CC35XX_SDHC_REG_CAPA_V30 BIT(25)
#define TI_CC35XX_SDHC_REG_CAPA_V33SUPP BIT(24)
/* CURCAP */
#define TI_CC35XX_SDHC_REG_CURCAP_ADDR 0x248
/* SDREV */
#define TI_CC35XX_SDHC_REG_SDREV_ADDR 0x2fc

/*********************/
/* IP Core Registers */
/*********************/
/* SYSCFG */
#define TI_CC35XX_CORE_REG_SYSCFG_ADDR 0x110
#define TI_CC35XX_CORE_REG_SYSCFG_SOFTRST BIT(1)
/* SYSSTAT */
#define TI_CC35XX_CORE_REG_SYSSTAT_ADDR 0x114
#define TI_CC35XX_CORE_REG_SYSSTAT_RSTDONE BIT(0)
/* CRDSTAT */
#define TI_CC35XX_CORE_REG_CRDSTAT_ADDR 0x124
/* SYSTEST */
#define TI_CC35XX_CORE_REG_SYSTEST_ADDR 0x128
/* CONFIG */
#define TI_CC35XX_CORE_REG_CONFIG_ADDR 0x12c
#define TI_CC35XX_CORE_REG_CONFIG_INITSEQ BIT(1)
/* PWRCNT */
#define TI_CC35XX_CORE_REG_PWRCNT_ADDR 0x130
/* TPSEL */
#define TI_CC35XX_CORE_REG_TPSEL_ADDR 0x1040
/* DMASEL */
#define TI_CC35XX_CORE_REG_DMASEL_ADDR 0x1048
/* DMAXIND */
#define TI_CC35XX_CORE_REG_DMAXIND_ADDR 0x1050
/* MEMCLK */
#define TI_CC35XX_CORE_REG_MEMCLK_ADDR 0x1054
/* EVTMODE */
#define TI_CC35XX_CORE_REG_EVTMODE_ADDR 0x10e0
/* DESCID */
#define TI_CC35XX_CORE_REG_DESCID_ADDR 0x10fc
/* STAT */
#define TI_CC35XX_CORE_REG_STAT_ADDR 0x1100
/* BUFDATA */
#define TI_CC35XX_CORE_REG_BUFDATA_ADDR 0x1110
/* CLKEN */
#define TI_CC35XX_CORE_REG_CLKEN_ADDR 0x4000
#define TI_CC35XX_CORE_REG_CLKEN_MEMCLK BIT(0)

/*********************/
/* Events */
/*********************/
/* Event/command status */
#define TI_CC35XX_EV_CMDCMPL TI_CC35XX_SDHC_REG_INTSTAT_CMDCMPL
#define TI_CC35XX_EV_TRCMP TI_CC35XX_SDHC_REG_INTSTAT_TRCMP
#define TI_CC35XX_EV_BLKGAP TI_CC35XX_SDHC_REG_INTSTAT_BLKGAP
#define TI_CC35XX_EV_DMAINT TI_CC35XX_SDHC_REG_INTSTAT_DMAINT
#define TI_CC35XX_EV_BUFWR TI_CC35XX_SDHC_REG_INTSTAT_BUFWR
#define TI_CC35XX_EV_BUFRDY TI_CC35XX_SDHC_REG_INTSTAT_BUFRDY

#define TI_CC35XX_EV_ERR TI_CC35XX_SDHC_REG_INTSTAT_ERR_INT
#define TI_CC35XX_EV_ERR_ALL_M 0xffff0000

#endif /* _TI_CC35XX_SDHC_ */
