# General configurations.

CONFIG_DEBUG=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_GPIO=y

# Comparator driver settings.

CONFIG_LPF3_ENABLE_COMPARATOR_INTERRUPT=n

# Settings related to tests.

CONFIG_LPCOMP_INPUT_COMBINATION_TEST_ENABLE=y
CONFIG_LPCOMP_EVENT_TEST_ENABLE=y
